image: lorisleiva/laravel-docker:latest

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
#    - cp .env.example .env
#    - php artisan key:generate
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
#      - .env

npm:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
      - public/css/
      - public/js/
      - public/images/

#phpunit:
#  stage: test
#  dependencies:
#    - composer
#  script:
#    - phpunit --coverage-text --colors=never

production:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/gitlab
    - chmod 600 ~/.ssh/gitlab
    - ssh-keyscan -p 22 209.145.62.20 > ~/.ssh/known_hosts
    - ssh-keygen -p -P $SSH_KEY_PASSWORD -N "" -f ~/.ssh/gitlab
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add ~/.ssh/gitlab
    - *change_file_permissions
    - php vendor/bin/dep launch stage=production -vvv
    # steps go here specifically, and after deploy because they
    # restart daemons that need the directory after symlinking
  environment:
    name: production
    url: https://www.spellslave.com
#  when: manual
  only:
    - main
