#thx atymic bby <3
name: CI-CD

on: push

jobs:
  build-js:
    name: Build Js/Css
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn Build
        run: |
          yarn install
          yarn build
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
#  test-php:
#    name: Test/Lint PHP
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-js] # Add test-php when re-enabled
    steps:
      - uses: actions/checkout@v1
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy to Prod
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
        run: |
          php vendor/bin/dep launch stage=production -vvv
